import type { Metadata } from "next";
import "./globals.css";
import "./style.css";

// Swiper
import "swiper/css";
import "swiper/css/bundle";
import "aos/dist/aos.css";
import Header from "@/components/Header/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-black`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
